# H3CN插件配置文件
# 特别提醒，务必保证该文件为UTF8无BOM编码

# 通用配置
[General]
TextColor = true # 兼容SoD_SP的彩色字体插件

# 如果没特殊需要不需要动这块
[MessageBox]
MinLineWidth = 0    # 最小行宽度
MaxLineWidth = 400  # 最大行宽度

# 字体映射定义
# Name: H3字体名称（切勿修改）
# ExtFont: H3字体对应的点阵字体
# Height: 点阵字体高
# Width: 点阵字体宽
# MarginLeft: 左边距
# MarginRight: 右边距
# MarginBottom: 行距修正

[[Fonts]]
Name = "tiny.fnt"
ExtFont = "Fonts/Hzk_Small"
Height = 12
Width = 12
MarginLeft = 1
MarginRight = 0
MarginBottom = 0
DrawShadow = false

[[Fonts]]
Name = "smalfont.fnt"
ExtFont = "Fonts/Hzk_Small"
Height = 12
Width = 12
MarginLeft = 1
MarginRight = 0
MarginBottom = 0
DrawShadow = true

[[Fonts]]
Name = "medfont.fnt"
ExtFont = "Fonts/Hzk_Medium"
Height = 16
Width = 16
MarginLeft = 1
MarginRight = 0
MarginBottom = 0
DrawShadow = true

[[Fonts]]
Name = "bigfont.fnt"
ExtFont = "Fonts/Hzk_Big"
Height = 24
Width = 24
MarginLeft = 2
MarginRight = 0
MarginBottom = 0
DrawShadow = true

[[Fonts]]
Name = "calli10r.fnt"
ExtFont = "Fonts/Hzk_Small"
Height = 12
Width = 12
MarginLeft = 1
MarginRight = 0
MarginBottom = 0
DrawShadow = true

[[Fonts]]
Name = "credits.fnt"
ExtFont = "Fonts/Hzk_Big"
Height = 24
Width = 24
MarginLeft = 2
MarginRight = 0
MarginBottom = 0
DrawShadow = true

[[Fonts]]
Name = "hiscore.fnt"
ExtFont = "Fonts/Hzk_Small"
Height = 12
Width = 12
MarginLeft = 1
MarginRight = 0
MarginBottom = 0
DrawShadow = true

[[Fonts]]
Name = "times08r.fnt"
ExtFont = "Fonts/Hzk_Small"
Height = 12
Width = 12
MarginLeft = 1
MarginRight = 0
MarginBottom = 0
DrawShadow = true

[[Fonts]]
Name = "verd10b.fnt"
ExtFont = "Fonts/Hzk_Small"
Height = 12
Width = 12
MarginLeft = 1
MarginRight = 0
MarginBottom = 0
DrawShadow = true
